version: '3.9'
services:
  server:
    container_name: server
    build:
      context: ./
      dockerfile: server.dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./config.json:/app/config.json
      - ./tests.yaml:/app/tests.yaml
      - ./certs/private_key.pem:/app/certs/private_key.pem
      - ./certs/public_key.pem:/app/certs/public_key.pem
    env_file:
      - env/server.env
    networks:
      backend:
    depends_on:
      db:
        condition: "service_healthy"
      minio:
        condition: "service_healthy"

  db:
    container_name: db
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - env/postgres.env
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      backend:

  minio:
    container_name: minio
    image: minio/minio
    command: server --console-address :9005 /data
    ports:
      - '9000:9000'
      - '9005:9005'
    env_file:
      - env/minio.env
    restart: always
    volumes:
      - minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      backend:

volumes:
  minio-data:
  db-data:
    driver: local

networks:
  backend:
