version: '3.9'
services:
  server:
    container_name: server
    build:
      context: ./infra
      dockerfile: server.dockerfile
    restart: always
    ports:
      - "8081:8081"
    environment:
      - CONFIG_FILE_PATH=/app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./test.yaml:/app/test.yaml
      - ./certs/private.pem:/app/certs/private.pem
      - ./certs/public.pem:/app/certs/public.pem
    networks:
      backend:
    depends_on:
      db:
        condition: "service_healthy"
      mino:
        condition: "service_healthy"

  db:
    container_name: db
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      backend:

  minio:
    container_name: minio
    image: minio/minio
    command: server --console-address :9005 /data
    ports:
      - '9000:9000'
      - '9005:9005'
    environment:
      - MINIO_ROOT_USER=test
      - MINIO_ROOT_PASSWORD=Ro2uym0AbpzwIy7vXwKcBRpkm2aQG3I0fiyq9LfzKRBm20dnwE1DejR31pz8NsyqvF0V38rqmo
    restart: always
    volumes:
      - minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      backend:

volumes:
  minio-data:
  db-data:

networks:
  backend: